export const products = [
  {
    name: "لاک ناخن براق",
    code: "NA001",
    category: "لاک",
    price: 120000,
    discountPrice: 100000,
    available: true,
    color: ["قرمز", "صورتی", "نارنجی"],
    shortDescription: "لاک با پوشش بالا و ماندگاری طولانی",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.5, votes: 120 },
    releaseDate: "01/01/1404",
    sale: 150,
    url: "lak-nakhon-baraq",
    img: "",
  },
  {
    name: "شامپو ضد ریزش",
    code: "SH002",
    category: "شامپو",
    price: 250000,
    available: true,
    shortDescription: "شامپو تقویت‌کننده فولیکول مو",
    country: "ترکیه",
    brand: "مراقبت مو",
    rating: { score: 4.2, votes: 95 },
    releaseDate: "05/01/1404",
    sale: 120,
    url: "shampoo-zed-rizesh",
    img: "",
  },
  {
    name: "صابون گیاهی",
    code: "SO003",
    category: "صابون",
    price: 60000,
    discountPrice: 50000,
    available: false,
    shortDescription: "صابون ملایم با عصاره گیاهان طبیعی",
    country: "ایران",
    brand: "صابون گیاهی",
    rating: { score: 4.7, votes: 80 },
    releaseDate: "10/01/1404",
    sale: 100,
    url: "saboon-giyahi",
    img: "",
  },
  {
    name: "رژ لب مات",
    code: "RL004",
    category: "رژ لب",
    price: 180000,
    discountPrice: 150000,
    available: true,
    color: ["صورتی", "قرمز", "مرجانی"],
    shortDescription: "رژ لب مات با ماندگاری ۸ ساعت",
    country: "فرانسه",
    brand: "لیپلکس",
    rating: { score: 4.6, votes: 200 },
    releaseDate: "15/01/1404",
    sale: 250,
    url: "roj-lab-mat",
    img: "",
  },
  {
    name: "رژگونه گلبهی",
    code: "RG005",
    category: "رژگونه",
    price: 140000,
    available: true,
    color: ["گلبهی", "هلویی", "مرجانی"],
    shortDescription: "رژگونه سبک و طبیعی",
    country: "ایتالیا",
    brand: "بلاش می",
    rating: { score: 4.3, votes: 60 },
    releaseDate: "20/01/1404",
    sale: 100,
    url: "rojgooneh-golbehi",
    img: "",
  },
  {
    name: "ریمل حجم دهنده",
    code: "RM006",
    category: "ریمل",
    price: 160000,
    discountPrice: 140000,
    available: true,
    color: ["مشکی"],
    shortDescription: "ریمل با حجم دهی فوق العاده",
    country: "آلمان",
    brand: "آی مکس",
    rating: { score: 4.8, votes: 150 },
    releaseDate: "25/01/1404",
    sale: 200,
    url: "rimel-hajm-dahande",
    img: "",
  },
  {
    name: "سایه چشم دودی",
    code: "SC007",
    category: "سایه چشم",
    price: 130000,
    available: false,
    color: ["دودی", "قهوه‌ای", "مشکی"],
    shortDescription: "سایه چشم با پوشش یکنواخت",
    country: "فرانسه",
    brand: "گلم آیز",
    rating: { score: 4.4, votes: 70 },
    releaseDate: "01/02/1404",
    sale: 100,
    url: "saye-cheshm-doodi",
    img: "",
  },
  {
    name: "لاک ناخن شاین",
    code: "NA008",
    category: "لاک",
    price: 110000,
    discountPrice: 95000,
    available: true,
    color: ["نارنجی", "طلایی", "صورتی"],
    shortDescription: "لاک براق و مقاوم در برابر ترک خوردن",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.1, votes: 90 },
    releaseDate: "05/02/1404",
    sale: 120,
    url: "lak-nakhon-shine",
    img: "",
  },
  {
    name: "شامپو نرم کننده",
    code: "SH009",
    category: "شامپو",
    price: 230000,
    available: true,
    shortDescription: "شامپو نرم کننده و خوشبو",
    country: "ترکیه",
    brand: "مراقبت مو",
    rating: { score: 4.3, votes: 110 },
    releaseDate: "10/02/1404",
    sale: 120,
    url: "shampoo-narm-konande",
    img: "",
  },
  {
    name: "صابون زیتون",
    code: "SO010",
    category: "صابون",
    price: 70000,
    discountPrice: 60000,
    available: true,
    shortDescription: "صابون ملایم با عصاره زیتون",
    country: "ایران",
    brand: "صابون گیاهی",
    rating: { score: 4.5, votes: 75 },
    releaseDate: "15/02/1404",
    sale: 120,
    url: "saboon-zeytoon",
    img: "",
  },
  {
    name: "رژ لب مخملی",
    code: "RL011",
    category: "رژ لب",
    price: 190000,
    available: false,
    color: ["قرمز", "صورتی", "مرجانی"],
    shortDescription: "رژ لب بافت مخملی و ماندگار",
    country: "فرانسه",
    brand: "لیپلکس",
    rating: { score: 4.7, votes: 180 },
    releaseDate: "20/02/1404",
    sale: 200,
    url: "roj-lab-makhmali",
    img: "",
  },
  {
    name: "رژگونه هلویی",
    code: "RG012",
    category: "رژگونه",
    price: 150000,
    discountPrice: 130000,
    available: true,
    color: ["هلویی", "گلبهی", "مرجانی"],
    shortDescription: "رژگونه بافت سبک و طبیعی",
    country: "ایتالیا",
    brand: "بلاش می",
    rating: { score: 4.4, votes: 65 },
    releaseDate: "25/02/1404",
    sale: 100,
    url: "rojgooneh-holooei",
    img: "",
  },
  {
    name: "ریمل ضد آب",
    code: "RM013",
    category: "ریمل",
    price: 170000,
    available: true,
    color: ["مشکی"],
    shortDescription: "ریمل با ماندگاری طولانی و ضد آب",
    country: "آلمان",
    brand: "آی مکس",
    rating: { score: 4.9, votes: 140 },
    releaseDate: "01/03/1404",
    sale: 180,
    url: "rimel-zed-ab",
    img: "",
  },
  {
    name: "سایه چشم اکلیلی",
    code: "SC014",
    category: "سایه چشم",
    price: 135000,
    discountPrice: 120000,
    available: true,
    color: ["طلایی", "نقره‌ای", "بژ"],
    shortDescription: "سایه چشم با جلوه اکلیلی",
    country: "فرانسه",
    brand: "گلم آیز",
    rating: { score: 4.5, votes: 80 },
    releaseDate: "05/03/1404",
    sale: 120,
    url: "saye-cheshm-aklili",
    img: "",
  },
  {
    name: "لاک ناخن مات",
    code: "NA015",
    category: "لاک",
    price: 125000,
    available: false,
    color: ["آبی", "سبز", "بنفش"],
    shortDescription: "لاک مات با پوشش یکنواخت",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.2, votes: 95 },
    releaseDate: "10/03/1404",
    sale: 120,
    url: "lak-nakhon-mat",
    img: "",
  },
  {
    name: "شامپو ضد شوره",
    code: "SH016",
    category: "شامپو",
    price: 240000,
    discountPrice: 210000,
    available: true,
    shortDescription: "شامپو موثر در رفع شوره سر",
    country: "ترکیه",
    brand: "مراقبت مو",
    rating: { score: 4.3, votes: 100 },
    releaseDate: "15/03/1404",
    sale: 120,
    url: "shampoo-zed-shoore",
    img: "",
  },
  {
    name: "صابون سفید کننده",
    code: "SO017",
    category: "صابون",
    price: 65000,
    available: true,
    shortDescription: "صابون سفید کننده و نرم کننده",
    country: "ایران",
    brand: "صابون گیاهی",
    rating: { score: 4.4, votes: 60 },
    releaseDate: "20/03/1404",
    sale: 100,
    url: "saboon-sefid-konande",
    img: "",
  },
  {
    name: "رژ لب نارنجی",
    code: "RL018",
    category: "رژ لب",
    price: 185000,
    discountPrice: 160000,
    available: true,
    color: ["نارنجی", "مرجانی", "قرمز"],
    shortDescription: "رژ لب جذاب و ماندگار",
    country: "فرانسه",
    brand: "لیپلکس",
    rating: { score: 4.6, votes: 190 },
    releaseDate: "25/03/1404",
    sale: 220,
    url: "roj-lab-narenji",
    img: "",
  },
  {
    name: "رژگونه مرجانی",
    code: "RG019",
    category: "رژگونه",
    price: 145000,
    available: false,
    color: ["مرجانی", "گلبهی", "هلویی"],
    shortDescription: "رژگونه با بافت سبک",
    country: "ایتالیا",
    brand: "بلاش می",
    rating: { score: 4.3, votes: 55 },
    releaseDate: "01/04/1404",
    sale: 100,
    url: "rojgooneh-marjani",
    img: "",
  },
  {
    name: "ریمل بلند کننده",
    code: "RM020",
    category: "ریمل",
    price: 165000,
    available: true,
    color: ["مشکی"],
    shortDescription: "ریمل برای بلند کردن مژه‌ها",
    country: "آلمان",
    brand: "آی مکس",
    rating: { score: 4.7, votes: 130 },
    releaseDate: "05/04/1404",
    sale: 160,
    url: "rimel-boland-konande",
    img: "",
  },
  {
    name: "سایه چشم مات",
    code: "SC021",
    category: "سایه چشم",
    price: 125000,
    available: true,
    color: ["قهوه‌ای", "مشکی", "بژ"],
    shortDescription: "سایه چشم مات و طبیعی",
    country: "فرانسه",
    brand: "گلم آیز",
    rating: { score: 4.3, votes: 70 },
    releaseDate: "10/04/1404",
    sale: 100,
    url: "saye-cheshm-mat",
    img: "",
  },
  {
    name: "لاک ناخن شاین طلایی",
    code: "NA022",
    category: "لاک",
    price: 130000,
    available: true,
    color: ["طلایی", "نارنجی"],
    shortDescription: "لاک براق طلایی",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.5, votes: 110 },
    releaseDate: "15/04/1404",
    sale: 120,
    url: "lak-nakhon-shine-talaei",
    img: "",
  },
  {
    name: "شامپو کودک",
    code: "SH023",
    category: "شامپو",
    price: 200000,
    available: true,
    shortDescription: "شامپو ملایم برای کودکان",
    country: "ترکیه",
    brand: "مراقبت مو",
    rating: { score: 4.2, votes: 90 },
    releaseDate: "20/04/1404",
    sale: 100,
    url: "shampoo-koodak",
    img: "",
  },
  {
    name: "صابون ضد جوش",
    code: "SO024",
    category: "صابون",
    price: 75000,
    available: false,
    shortDescription: "صابون ضد جوش و نرم کننده",
    country: "ایران",
    brand: "صابون گیاهی",
    rating: { score: 4.5, votes: 70 },
    releaseDate: "25/04/1404",
    sale: 100,
    url: "saboon-zed-josh",
    img: "",
  },
  {
    name: "رژ لب صورتی",
    code: "RL025",
    category: "رژ لب",
    price: 180000,
    available: true,
    color: ["صورتی", "مرجانی"],
    shortDescription: "رژ لب صورتی و جذاب",
    country: "فرانسه",
    brand: "لیپلکس",
    rating: { score: 4.6, votes: 170 },
    releaseDate: "01/05/1404",
    sale: 200,
    url: "roj-lab-sorati",
    img: "",
  },
  {
    name: "رژگونه برنزی",
    code: "RG026",
    category: "رژگونه",
    price: 150000,
    discountPrice: 140000,
    available: true,
    color: ["برنزی", "هلویی"],
    shortDescription: "رژگونه با رنگ برنزی طبیعی",
    country: "ایتالیا",
    brand: "بلاش می",
    rating: { score: 4.4, votes: 60 },
    releaseDate: "05/05/1404",
    sale: 100,
    url: "rojgooneh-barnzi",
    img: "",
  },
  {
    name: "ریمل تقویت کننده",
    code: "RM027",
    category: "ریمل",
    price: 175000,
    available: true,
    color: ["مشکی"],
    shortDescription: "ریمل با فرمول تقویتی برای مژه",
    country: "آلمان",
    brand: "آی مکس",
    rating: { score: 4.8, votes: 140 },
    releaseDate: "10/05/1404",
    sale: 160,
    url: "rimel-taghviyat-konande",
    img: "",
  },
  {
    name: "سایه چشم بژ",
    code: "SC028",
    category: "سایه چشم",
    price: 130000,
    available: true,
    color: ["بژ", "قهوه‌ای"],
    shortDescription: "سایه چشم ملایم و روزانه",
    country: "فرانسه",
    brand: "گلم آیز",
    rating: { score: 4.3, votes: 60 },
    releaseDate: "15/05/1404",
    sale: 100,
    url: "saye-cheshm-bezh",
    img: "",
  },
  {
    name: "لاک ناخن قرمز",
    code: "NA029",
    category: "لاک",
    price: 125000,
    available: true,
    color: ["قرمز"],
    shortDescription: "لاک قرمز براق و زیبا",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.6, votes: 100 },
    releaseDate: "20/05/1404",
    sale: 120,
    url: "lak-nakhon-ghermez",
    img: "",
  },
  {
    name: "شامپو تقویتی",
    code: "SH030",
    category: "شامپو",
    price: 260000,
    available: false,
    shortDescription: "شامپو تقویتی و مغذی",
    country: "ترکیه",
    brand: "مراقبت مو",
    rating: { score: 4.4, votes: 120 },
    releaseDate: "25/05/1404",
    sale: 130,
    url: "shampoo-taghviyati",
    img: "",
  },
  {
    name: "صابون ضد حساسیت",
    code: "SO031",
    category: "صابون",
    price: 68000,
    available: true,
    shortDescription: "صابون ملایم برای پوست حساس",
    country: "ایران",
    brand: "صابون گیاهی",
    rating: { score: 4.5, votes: 80 },
    releaseDate: "01/06/1404",
    sale: 100,
    url: "saboon-zed-hassasiyat",
    img: "",
  },
  {
    name: "رژ لب نارنجی مات",
    code: "RL032",
    category: "رژ لب",
    price: 190000,
    available: true,
    color: ["نارنجی"],
    shortDescription: "رژ لب مات و ماندگار",
    country: "فرانسه",
    brand: "لیپلکس",
    rating: { score: 4.6, votes: 160 },
    releaseDate: "05/06/1404",
    sale: 180,
    url: "roj-lab-narenji-mat",
    img: "",
  },
  {
    name: "رژگونه هلویی روشن",
    code: "RG033",
    category: "رژگونه",
    price: 155000,
    available: true,
    color: ["هلویی روشن", "گلبهی"],
    shortDescription: "رژگونه روشن و طبیعی",
    country: "ایتالیا",
    brand: "بلاش می",
    rating: { score: 4.4, votes: 60 },
    releaseDate: "10/06/1404",
    sale: 100,
    url: "rojgooneh-holooei-roshan",
    img: "",
  },
  {
    name: "ریمل حجم‌دهنده اکسترا",
    code: "RM034",
    category: "ریمل",
    price: 180000,
    available: true,
    color: ["مشکی"],
    shortDescription: "ریمل با حجم‌دهی فوق‌العاده",
    country: "آلمان",
    brand: "آی مکس",
    rating: { score: 4.7, votes: 150 },
    releaseDate: "15/06/1404",
    sale: 160,
    url: "rimel-hajm-dahande-extra",
    img: "",
  },
  {
    name: "سایه چشم اکلیلی طلایی",
    code: "SC035",
    category: "سایه چشم",
    price: 140000,
    available: true,
    color: ["طلایی", "بژ"],
    shortDescription: "سایه چشم اکلیلی برای مهمانی",
    country: "فرانسه",
    brand: "گلم آیز",
    rating: { score: 4.5, votes: 70 },
    releaseDate: "20/06/1404",
    sale: 100,
    url: "saye-cheshm-aklili-talaei",
    img: "",
  },
  {
    name: "لاک ناخن صورتی",
    code: "NA036",
    category: "لاک",
    price: 120000,
    available: true,
    color: ["صورتی"],
    shortDescription: "لاک صورتی با پوشش یکنواخت",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.4, votes: 90 },
    releaseDate: "25/06/1404",
    sale: 100,
    url: "lak-nakhon-sorati",
    img: "",
  },
  {
    name: "شامپو ضد چربی",
    code: "SH037",
    category: "شامپو",
    price: 245000,
    available: true,
    shortDescription: "شامپو مناسب موهای چرب",
    country: "ترکیه",
    brand: "مراقبت مو",
    rating: { score: 4.3, votes: 100 },
    releaseDate: "01/07/1404",
    sale: 120,
    url: "shampoo-zed-charbi",
    img: "",
  },
  {
    name: "صابون گیاهی آلوئه‌ورا",
    code: "SO038",
    category: "صابون",
    price: 72000,
    available: true,
    shortDescription: "صابون ملایم با عصاره آلوئه‌ورا",
    country: "ایران",
    brand: "صابون گیاهی",
    rating: { score: 4.5, votes: 75 },
    releaseDate: "05/07/1404",
    sale: 100,
    url: "saboon-aloevera",
    img: "",
  },
  {
    name: "رژ لب مخملی قرمز",
    code: "RL039",
    category: "رژ لب",
    price: 195000,
    available: true,
    color: ["قرمز"],
    shortDescription: "رژ لب با بافت مخملی",
    country: "فرانسه",
    brand: "لیپلکس",
    rating: { score: 4.6, votes: 180 },
    releaseDate: "10/07/1404",
    sale: 200,
    url: "roj-lab-makhmali-ghermez",
    img: "",
  },
  {
    name: "رژگونه هلویی مات",
    code: "RG040",
    category: "رژگونه",
    price: 160000,
    available: true,
    color: ["هلویی مات", "مرجانی"],
    shortDescription: "رژگونه مات و طبیعی",
    country: "ایتالیا",
    brand: "بلاش می",
    rating: { score: 4.4, votes: 65 },
    releaseDate: "15/07/1404",
    sale: 100,
    url: "rojgooneh-holooei-mat",
    img: "",
  },
  {
    name: "ریمل ضد ریزش",
    code: "RM041",
    category: "ریمل",
    price: 185000,
    available: true,
    color: ["مشکی"],
    shortDescription: "ریمل ضد ریزش و تقویت کننده",
    country: "آلمان",
    brand: "آی مکس",
    rating: { score: 4.8, votes: 140 },
    releaseDate: "20/07/1404",
    sale: 160,
    url: "rimel-zed-rizesh",
    img: "",
  },
  {
    name: "سایه چشم بژ مات",
    code: "SC042",
    category: "سایه چشم",
    price: 135000,
    available: true,
    color: ["بژ"],
    shortDescription: "سایه چشم مات روزانه",
    country: "فرانسه",
    brand: "گلم آیز",
    rating: { score: 4.3, votes: 60 },
    releaseDate: "25/07/1404",
    sale: 100,
    url: "saye-cheshm-bezh-mat",
    img: "",
  },
  {
    name: "لاک ناخن سبز",
    code: "NA043",
    category: "لاک",
    price: 125000,
    available: true,
    color: ["سبز"],
    shortDescription: "لاک سبز براق",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.5, votes: 95 },
    releaseDate: "01/08/1404",
    sale: 100,
    url: "lak-nakhon-sabz",
    img: "",
  },
  {
    name: "شامپو تقویتی مو خشک",
    code: "SH044",
    category: "شامپو",
    price: 255000,
    available: true,
    shortDescription: "شامپو برای موهای خشک و آسیب دیده",
    country: "ترکیه",
    brand: "مراقبت مو",
    rating: { score: 4.4, votes: 110 },
    releaseDate: "05/08/1404",
    sale: 120,
    url: "shampoo-taghviyati-khoshk",
    img: "",
  },
  {
    name: "صابون لایه بردار",
    code: "SO045",
    category: "صابون",
    price: 75000,
    available: true,
    shortDescription: "صابون ملایم لایه بردار پوست",
    country: "ایران",
    brand: "صابون گیاهی",
    rating: { score: 4.5, votes: 80 },
    releaseDate: "10/08/1404",
    sale: 100,
    url: "saboon-laye-bardar",
    img: "",
  },
  {
    name: "رژ لب هلویی",
    code: "RL046",
    category: "رژ لب",
    price: 185000,
    available: true,
    color: ["هلویی"],
    shortDescription: "رژ لب جذاب و ماندگار",
    country: "فرانسه",
    brand: "لیپلکس",
    rating: { score: 4.6, votes: 160 },
    releaseDate: "15/08/1404",
    sale: 180,
    url: "roj-lab-holooei",
    img: "",
  },
  {
    name: "رژگونه برنزی روشن",
    code: "RG047",
    category: "رژگونه",
    price: 155000,
    available: true,
    color: ["برنزی روشن", "هلویی"],
    shortDescription: "رژگونه روشن با بافت سبک",
    country: "ایتالیا",
    brand: "بلاش می",
    rating: { score: 4.4, votes: 65 },
    releaseDate: "20/08/1404",
    sale: 100,
    url: "rojgooneh-barnzi-roshan",
    img: "",
  },
  {
    name: "ریمل حجم‌دهنده مشکی",
    code: "RM048",
    category: "ریمل",
    price: 180000,
    available: true,
    color: ["مشکی"],
    shortDescription: "ریمل حجم دهنده فوق العاده",
    country: "آلمان",
    brand: "آی مکس",
    rating: { score: 4.7, votes: 150 },
    releaseDate: "25/08/1404",
    sale: 160,
    url: "rimel-hajm-dahande-meshki",
    img: "",
  },
  {
    name: "سایه چشم مات روزانه",
    code: "SC049",
    category: "سایه چشم",
    price: 130000,
    available: true,
    color: ["بژ", "قهوه‌ای"],
    shortDescription: "سایه چشم مات مناسب استفاده روزانه",
    country: "فرانسه",
    brand: "گلم آیز",
    rating: { score: 4.3, votes: 60 },
    releaseDate: "01/09/1404",
    sale: 100,
    url: "saye-cheshm-mat-rozane",
    img: "",
  },
  {
    name: "لاک ناخن بنفش",
    code: "NA050",
    category: "لاک",
    price: 125000,
    available: true,
    color: ["بنفش"],
    shortDescription: "لاک بنفش با پوشش عالی",
    country: "ایران",
    brand: "نايل پرو",
    rating: { score: 4.5, votes: 95 },
    releaseDate: "05/09/1404",
    sale: 100,
    url: "lak-nakhon-banafsh",
    img: "",
  },
];
